services:
  mt5:
    container_name: mt5
    image: mt5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
