services:
  mt5:
    container_name: mt5
    image: mt5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
      - 8001:8001
    env_file:
      - .env
