networks:
  portainer-nginx-proxy-manager_default: #change this to your network
    external: true

services:
  mt5_1:
    container_name: mt5_1
    image: mt5
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./config_1:/config
    ports:
      - 3001:3000
      - 8001:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_2:
    container_name: mt5_2
    image: mt5
    volumes:
      - ./config_2:/config
    ports:
      - 3002:3000
      - 8002:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_3:
    container_name: mt5_3
    image: mt5
    volumes:
      - ./config_3:/config
    ports:
      - 3003:3000
      - 8003:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_4:
    container_name: mt5_4
    image: mt5
    volumes:
      - ./config_4:/config
    ports:
      - 3004:3000
      - 8004:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_5:
    container_name: mt5_5
    image: mt5
    volumes:
      - ./config_5:/config
    ports:
      - 3005:3000
      - 8005:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_6:
    container_name: mt5_6
    image: mt5
    volumes:
      - ./config_6:/config
    ports:
      - 3006:3000
      - 8006:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_7:
    container_name: mt5_7
    image: mt5
    volumes:
      - ./config_7:/config
    ports:
      - 3007:3000
      - 8007:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_8:
    container_name: mt5_8
    image: mt5
    volumes:
      - ./config_8:/config
    ports:
      - 3008:3000
      - 8008:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_9:
    container_name: mt5_9
    image: mt5
    volumes:
      - ./config_9:/config
    ports:
      - 3009:3000
      - 8009:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mt5_10:
    container_name: mt5_10
    image: mt5
    volumes:
      - ./config_10:/config
    ports:
      - 3010:3000
      - 8010:8001
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 4G
        reservations:
          cpus: "0.25"
          memory: 512M
    restart: unless-stopped
    networks:
      - portainer-nginx-proxy-manager_default #change this to your network
    logging:
      options:
        max-size: "10m"
        max-file: "3"
